default_output: "stdout"
#default_output: "elasticsearch"
pcap_extracted_fields:
  - http.request.method
  - tls.handshake.extensions_server_name
  - tcp.reassembled.data
pcap_field_conditions:
  #- http_request_method:
      #match: exists
  #- http_request_method: "GET"
  #- http_request_method: ["GET", "POST", "CONNECT"]
  #- http_request_method:
      #match: exact
      #value:
        #- "GET"
        #- "POST"
        #- "CONNECT"
  #- http_request_method:
      #match: case_ignore
      #value: "get"
  - http_request_method:
      match: regex
      value: ["^P.*","^G.*","^C.*"]
      #value: ".*"
  #- http_request_method:
      #match: regex
      #value: ["^P.*","^G.*","^C.*"]
      #value: ".*"
    #tcp_dstport: [80, 3128]
    #tcp_dstport:
      #- 80
      #- 3128
  - tls_handshake_extensions_server_name:
      match: exists
  - tcp_reassembled_data:
      match: regex
      value: ".*0d0a0d0a4d5a.*"
max_field_len: 1024
default_action: "filter"
#default_action: "agg"
#agg:
  #type: "community_id"
  #extracted_result_fields:
    #- http_request_method
    #- tcp_reassembled_data
    #- tls_handshake_extensions_server_name
#elasticsearch:
  #address: http://log.example.com:9200
  #document_id: "community_id"
  #bulk: 128
  #address: https://log.example.com:9200
  #user_name: elastic
  #password: elastic
  #ssl_verification_disabled: true
  #ssl_ca_certificate: "../../es_test/certs/ca/ca.crt"
#tshark:
  #exe: "/usr/bin/tshark"
  #args:
    #- "-d"
    #- "tcp.port==80,http"

